language: generic

# Dependency of the minted package
#before_install:
# - sudo apt-get install python-pygments
#install:
# - source ./texlive/texlive_install.sh
#cache:
#  directories:
#    - /tmp/texlive
#    - $HOME/.texlive
# Change working directory so including files will work
#before_script: cd $TRAVIS_BUILD_DIR/src/
script:
 - make
#- mkdir _build
# Prefix command with travis_wait x so it times out after 3 mins, because when the LaTeX doesn't compile pdflatex just hangs instead of quitting.
#- travis_wait 3 pdflatex -output-directory _build -shell-escape ./main.tex
# Compile twice to fix possible references
#- travis_wait 3 pdflatex -output-directory _build -shell-escape ./main.tex